### ISSUE TITLE
Clarification Question

### ISSUE THREAD

**Issue by trdavidson** [szymonmaszke/torchlambda#10]
Hi there - this project looks really cool. Short question - is it possible to deploy pytorch as a lambda layer s.t. it only hosts the pytorch package and can thus be imported from other layers/funcs using torchlambda?

Thanks!

**Comment by szymonmaszke** [comment]
Statically compiled PyTorch C++ frontend is included when you run `torchlambda build` and it is deployed as a package to AWS's Lambda. You can use anything the C++ frontend (libtorch) can use in your C++ deployment code and can use most (any?) models compiled by torchscript provided they fit on a single layer (up to `50Mb` size, at least currently).

Does that answer your question?

**Comment by trdavidson** [comment]
hmm i see - ok I should dive more into how to best use torchscript in that case. Thanks for getting back!
