### ISSUE TITLE
Error in aws lambda not local 

### ISSUE THREAD

**Issue by arunpatala** [szymonmaszke/torchlambda#8]
Hi,

Thanks for such a great repository. It fits very well to my usecase.

I have been following the tutorial and I was able to get the results with testing with local deployment. But when I am hitting the main lambda function, I am getting errors like "Invalid base64" for both normal request and also base64 encoding.

Please let me know any pointers.

And thanks again for your work.
Arun

**Comment by szymonmaszke** [comment]
> I have been following the tutorial and I was able to get the results with testing with local deployment.

So I assume you followed [ResNet18 tutorial](https://github.com/szymonmaszke/torchlambda/wiki/ResNet18-deployment-on-AWS-Lambda) points `1-5` successfully and followed the rest from [Testing local](https://github.com/szymonmaszke/torchlambda/wiki/Test-Lambda-deployment-locally) successfully as well, right? 

And now you are trying [base64](https://github.com/szymonmaszke/torchlambda/wiki/base64-image-encoding) and the source is on AWS Lambda instance already, right?

If so, could you show me the code with which you are making request? Some more details would be great to have.

**Comment by arunpatala** [comment]
Hi,

I was trying both base64 and without it with lambda which doesnt work . Both works locally but not with lambda. I will try to get more information for debugging.

Thanks for replying
Arun

**Comment by szymonmaszke** [comment]
`base64` was checked against CD lately (a week ago?) and worked fine. Make sure shapes are correct on both sides (`torchlambda` deployed package and your source code).

**Comment by arunpatala** [comment]
Thanks 

I will close this as this is not a real issue. I will try to follow your instructions. I am not able to get it working, but I will try to figure it out. You have a good code base.

I like your work.
Arun

**Comment by trdavidson** [comment]
Hi - was initially also not able to get this working on aws, but using the following flag solved it for me:
`--cli-binary-format raw-in-base64-out`
